import Link from 'next/link'
import { ArrowRight, Check, ChevronDown, Play, Quote } from 'lucide-react'
import { courses, faqs, instructors, testimonials } from '@/lib/site-data'
import { CourseCard } from '@/components/course-card'
import { Shell } from '@/components/site-shell'

export default function Home() { return <Shell><main>
  <section className="overflow-hidden bg-secondary/40"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-16 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8 lg:py-24"><div><h1 className="max-w-2xl font-serif text-5xl leading-[.92] tracking-tight text-balance sm:text-6xl lg:text-7xl">Accredited <span className="text-primary">Online Language Classes</span></h1><p className="mt-7 max-w-lg text-lg leading-8 text-muted-foreground">Small-group courses for people who want to think deeply, make boldly, and grow with others.</p><div className="mt-9 flex flex-wrap items-center gap-4"><Link href="/enroll" className="rounded-full bg-primary px-6 py-3.5 text-sm font-bold text-primary-foreground transition-transform hover:-translate-y-0.5">Enroll Now</Link><Link href="/courses" className="inline-flex items-center gap-2 px-3 py-3 text-sm font-bold hover:text-primary">Explore courses <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-12 flex items-center gap-8 border-t border-border pt-6"><div><strong className="font-serif text-3xl">4.9</strong><p className="mt-1 text-xs text-muted-foreground">average student rating</p></div><div className="h-10 w-px bg-border" /><div><strong className="font-serif text-3xl">94%</strong><p className="mt-1 text-xs text-muted-foreground">finish with a project</p></div></div></div><div className="relative"><div className="overflow-hidden rounded-[2rem] bg-primary p-3 shadow-xl"><img src="/hero-section.jpg" alt="Alia Online language class" className="aspect-[4/5] w-full rounded-[1.5rem] object-cover" /></div><div className="absolute -bottom-5 -left-3 max-w-[210px] rounded-2xl border border-border bg-card p-4 shadow-lg sm:-left-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">Next cohort</p><p className="mt-2 font-serif text-xl">Spring studios open</p><Link href="/signup" className="mt-3 inline-flex text-sm font-bold hover:text-primary">Save your place <ArrowRight className="ml-2 h-4 w-4" /></Link></div></div></div></section>
  {/* <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-primary">Choose your direction</p><h2 className="mt-4 font-serif text-4xl tracking-tight sm:text-5xl">Learn by doing.</h2></div><Link href="/courses" className="inline-flex items-center gap-2 text-sm font-bold hover:text-primary">View all courses <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-10 grid gap-5 md:grid-cols-3">{courses.filter(c => c.featured).map(course => <CourseCard key={course.slug} course={course} />)}</div></section> */}
  <section className="bg-foreground text-background"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-2 lg:items-center lg:px-8 lg:py-28"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-primary">The Alia Online method</p><h2 className="mt-4 max-w-xl font-serif text-4xl leading-tight sm:text-5xl">A better kind of classroom.</h2><p className="mt-6 max-w-lg text-base leading-7 text-background/65">We make room for questions, useful struggle, and the confidence that comes from making something real.</p><Link href="/about" className="mt-8 inline-flex items-center gap-2 rounded-full bg-primary px-5 py-3 text-sm font-bold text-primary-foreground">Our approach <ArrowRight className="h-4 w-4" /></Link></div><div className="grid gap-3 sm:grid-cols-2">{['Small groups, real attention', 'Projects over worksheets', 'A community that stays', 'Skills for a changing world'].map((item, i) => <div key={item} className="border-t border-background/20 py-5"><span className="text-sm text-primary">0{i + 1}</span><p className="mt-4 font-serif text-xl">{item}</p></div>)}</div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="grid gap-10 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-primary">From our learners</p><h2 className="mt-4 font-serif text-4xl leading-tight">Momentum looks different for everyone.</h2></div><div className="grid gap-5 sm:grid-cols-2">{testimonials.map(t => <figure key={t.name} className="rounded-2xl bg-secondary p-6"><Quote className="h-7 w-7 text-primary" /><blockquote className="mt-5 text-lg leading-7">“{t.quote}”</blockquote><figcaption className="mt-8 text-sm"><strong>{t.name}</strong><span className="ml-2 text-muted-foreground">{t.detail}</span></figcaption></figure>)}</div></div></section>
  <section className="border-t border-border"><div className="mx-auto max-w-3xl px-5 py-20 lg:py-24"><p className="text-xs font-bold uppercase tracking-[.22em] text-primary">Questions, answered</p><h2 className="mt-4 font-serif text-4xl">Curious? Good.</h2><div className="mt-8 divide-y divide-border">{faqs.map(([q, a]) => <details key={q} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between font-semibold">{q}<ChevronDown className="h-5 w-5 transition-transform group-open:rotate-180" /></summary><p className="mt-3 max-w-2xl pr-8 text-sm leading-6 text-muted-foreground">{a}</p></details>)}</div></div></section>
  <section className="mx-auto max-w-7xl px-5 pb-20 lg:px-8 lg:pb-28"><div className="rounded-[2rem] bg-primary px-6 py-12 text-primary-foreground sm:px-12 lg:flex lg:items-center lg:justify-between lg:py-16"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-primary-foreground/70">Your next chapter</p><h2 className="mt-3 max-w-xl font-serif text-4xl leading-tight">Make space for what could happen.</h2></div><Link href="/signup" className="mt-8 inline-flex items-center gap-2 rounded-full bg-background px-6 py-3.5 text-sm font-bold text-foreground lg:mt-0">Start learning <ArrowRight className="h-4 w-4" /></Link></div></section>
</main></Shell> }
