import Link from 'next/link'
import { ArrowRight, Check, Clock3, GraduationCap, UsersRound } from 'lucide-react'
import { Shell } from '@/components/site-shell'

const units = ['Introductions and Greetings', 'The Family', 'The Home', 'Daily Life', 'Food and Drink', 'Studies and School', 'Work and Occupations']
const included = ['Full access to digital course materials', 'Activity Center access', 'Practice Center access', 'Direct communication with the teacher through the course discussion feature', 'Ongoing academic support throughout the program']
const steps = [
  ['Register and pay', 'Register through aliaonline.org and pay $450 per student, or use the sibling discount code when applicable.'],
  ['Share availability', 'After payment, submit the student’s full preferred class availability by day and time in the CST time zone.'],
  ['Schedule coordination', 'ALIA shares the family’s availability with Studio Arabiya in Egypt.'],
  ['Placement and teacher assignment', 'Studio Arabiya schedules a brief placement interview, assigns a teacher, and confirms the class schedule.'],
  ['Receive platform access', 'ALIA provides login details for Studio Arabiya’s learning platform, which is separate from aliaonline.org.'],
]

export default function ArabicCoursePage() {
  return <Shell><main>
    <section className="overflow-hidden bg-[#0E223C] text-white">
      <div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[1.15fr_.85fr] lg:items-center lg:px-8 lg:py-28">
        <div><p className="text-sm font-extrabold uppercase tracking-[.22em] text-[#9fd7d2]">ALIA Arabic Program</p><h1 className="mt-5 max-w-3xl font-serif text-5xl leading-[.98] tracking-tight sm:text-6xl">Arabic Program for World Language Credit</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/75">Private, flexible online Arabic instruction for students ages 11+.</p><div className="mt-9 flex flex-wrap gap-4"><Link href="/enroll?course=arabic" className="inline-flex items-center gap-2 rounded-full bg-white px-7 py-3.5 font-bold text-[#0E223C] transition-transform hover:-translate-y-0.5">Enroll in Arabic <ArrowRight className="h-4 w-4" /></Link></div></div><div className="rounded-3xl border border-white/15 bg-white/10 p-7 backdrop-blur"><UsersRound className="h-9 w-9 text-[#9fd7d2]" /><h2 className="mt-5 font-serif text-3xl">Private 1-on-1 instruction</h2><p className="mt-4 leading-7 text-white/75">Every Arabic student learns through private instruction. This program is different from ALIA’s small-group Urdu format and is delivered by Studio Arabiya instructors in Egypt, not ALIA School staff.</p></div>
      </div>
    </section>

    <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28">
      <div className="mx-auto max-w-4xl text-center"><p className="text-sm font-extrabold uppercase tracking-[.22em] text-[#0E223C]">Credit that travels with you</p><h2 className="mt-4 font-serif text-4xl tracking-tight text-[#0E223C] sm:text-5xl">Build a recognized language record</h2></div><div className="mt-12 grid gap-5 md:grid-cols-2"><article className="rounded-3xl border border-[#0E223C]/15 bg-secondary/40 p-7"><Clock3 className="h-7 w-7 text-[#0E223C]" /><h3 className="mt-5 text-2xl font-bold text-[#0E223C]">0.5 credit pathway</h3><p className="mt-3 leading-7 text-muted-foreground">Complete 24 classes of 45 minutes each, plus all program requirements, to earn 0.5 high school World Language credit.</p></article><article className="rounded-3xl border border-[#0E223C]/15 bg-secondary/40 p-7"><GraduationCap className="h-7 w-7 text-[#0E223C]" /><h3 className="mt-5 text-2xl font-bold text-[#0E223C]">1.0 credit pathway</h3><p className="mt-3 leading-7 text-muted-foreground">Complete 48 classes of 45 minutes each, plus program requirements, to earn 1.0 high school World Language credit and an official ALIA School transcript.</p></article></div><div className="mx-auto mt-8 max-w-4xl rounded-2xl border border-border p-6 text-justify leading-7 text-muted-foreground">Students may continue through the sequence for up to four years of World Language credit, with separate registration for each level. ALIA School is Cognia-accredited, and transcripts can be presented to schools, colleges, and universities. Frisco, Texas credits are accepted at 31 middle and high schools; families should follow Frisco ISD’s Alternative Language Program Guidelines through their school counselor. Students in all other districts must obtain approval directly from their school counselor or district for credit acceptance.</div>
    </section>

    <section className="bg-secondary/45"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-2 lg:px-8 lg:py-28"><div><p className="text-sm font-extrabold uppercase tracking-[.22em] text-[#0E223C]">Placement and learning levels</p><h2 className="mt-4 font-serif text-4xl tracking-tight text-[#0E223C]">A starting point that fits each student</h2><p className="mt-6 text-justify leading-8 text-muted-foreground">The Arabic program is open to all proficiency levels. Beginners begin with foundational reading, while students with prior experience start further into the textbook. Every student has a brief placement interview with a teacher after registering and before classes begin, confirming the best starting point.</p></div><div className="rounded-3xl bg-white p-7 shadow-sm"><p className="text-sm font-bold text-[#0E223C]">Book 1 curriculum</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Al-Arabiyyah Bayna Yadayk builds vocabulary, grammar, conversation, listening, reading, and writing.</p><ul className="mt-6 grid gap-3 sm:grid-cols-2">{units.map((unit) => <li key={unit} className="flex items-start gap-2 text-sm"><Check className="mt-0.5 h-4 w-4 shrink-0 text-[#0E223C]" />{unit}</li>)}</ul></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="grid gap-12 lg:grid-cols-2"><div><p className="text-sm font-extrabold uppercase tracking-[.22em] text-[#0E223C]">What&apos;s included</p><h2 className="mt-4 font-serif text-4xl tracking-tight text-[#0E223C]">Support beyond the lesson</h2><ul className="mt-8 space-y-4">{included.map((item) => <li key={item} className="flex gap-3 leading-7 text-muted-foreground"><Check className="mt-1 h-5 w-5 shrink-0 text-[#0E223C]" />{item}</li>)}</ul></div><div className="rounded-3xl bg-[#0E223C] p-8 text-white"><p className="text-sm font-extrabold uppercase tracking-[.2em] text-[#9fd7d2]">Teachers</p><h2 className="mt-4 font-serif text-4xl">Expert Arabic educators</h2><p className="mt-6 leading-8 text-white/75">Studio Arabiya instructors are graduates of Al-Azhar University and other prestigious colleges, with more than 10 years of experience teaching Arabic.</p><div className="mt-10 border-t border-white/15 pt-7"><p className="font-bold text-[#9fd7d2]">Tuition: $450 per student</p><p className="mt-3 leading-7 text-white/75">Siblings at the same proficiency level may attend the same private class together. Each child must register separately; use the sibling coupon code during registration for a 10% discount.</p></div></div></div></section>

    <section className="bg-[#0E223C] text-white"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-extrabold uppercase tracking-[.22em] text-[#9fd7d2]">Payment and access process</p><h2 className="mt-4 font-serif text-4xl sm:text-5xl">What happens after you enroll</h2><p className="mt-6 text-lg leading-8 text-white/75">Please allow 7–10 business days from payment to the first class. This timeline is normal for coordinating private instruction, placement, and scheduling.</p></div><div className="mt-12 grid gap-4 md:grid-cols-5">{steps.map(([title, detail], index) => <article key={title} className="rounded-2xl border border-white/15 bg-white/10 p-5"><span className="text-sm font-bold text-[#9fd7d2]">0{index + 1}</span><h3 className="mt-4 font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-white/70">{detail}</p></article>)}</div><div className="mx-auto mt-12 max-w-3xl rounded-3xl bg-white p-7 text-[#0E223C]"><p className="text-sm font-extrabold uppercase tracking-[.18em]">After registration</p><p className="mt-4 leading-7">Thank you for registering for Arabic classes with ALIA Online! We are excited to welcome you as you build confidence in Arabic, strengthen your language skills, and work toward earning World Language credit.</p><p className="mt-4 leading-7">We will contact you within 7–10 business days to schedule your private classes. Students earn 0.5 World Language credit after completing 24 private classes of 45 minutes each. An official transcript reflecting 1.0 World Language credit is issued by ALIA after two semesters, totaling 48 classes.</p><p className="mt-4 leading-7">We look forward to being part of your Arabic learning journey. Please contact us if you have any questions.</p></div></div></section>
  </main></Shell>
}
